version: "3"
services:
    openldap:
        build: ../docker-compose-openldap
        env_file: .env
        volumes:
            - ./ldap/config/slapd.conf:/etc/openldap/slapd.conf
            - ./ldap/config/slapd.ldif:/etc/openldap/slapd.ldif
            - ./ldap/data/:/var/lib/openldap/openldap-data/
            - ./ldap/import/:/var/lib/openldap/import/
